discreet_fracture_network_parameters:
  # These are the dimensions of the domain, that the fractures will be generated in
  # [1, 1] is a unit square with its middle point in the origin of the XYZ coordinates
  # [2, 1] would be a rectangle that also has its middle point in the origin
  # All types of rectangles (squares) are possible, the dimensions must not be less or equal to zero
  rectangle_dimensions: [1, 1]

  # SKB: interval [r_min, r_max]
  sample_range: [0.038, 169]

  # SKB: Fracture size scaling exponent k_r:
  # k_r is calibrated for the tectonic continuum: 2.55 to 2.79
  # k_r is calibrated by connectivity analysis: 2.55 to 3.45
  k_r: 2.5

  # SKB: interval [r_0, infty]
  diam_range: [0.038, 169]

  # Area density of fractures i.e. area of fractures per unit volume for interval [r_0, infty]
  # range p_32 [r_0, infty]: 0.59 to 2.60,
  p32_r_0_to_infty: 2

  # Statistics of the DFN
  fisher_orientation_parameters:
    # SKB: Trend (degrees): (2.5, 354.2)
    fisher_trend: 10
    # SKB: Plunge (degrees): (0.1, 85.4)
    fisher_plunge: 85
    # SKB: Fisher kappa:  (6.5, 42.9)
    fisher_concentration: 10
  von_mises_parameters:
    von_mises_trend: 0
    von_mises_concentration: 0

output_parameters:
  mesh_file_name: "mine_mesh"

gmsh_options_parameters:
  fracture_mesh_step: 0.03
  tolerance_initial_delaunay: 0.0001
  tolerance: 0.0005
  tolerance_boolean: 0.0001
